# Generated by Django 3.2.18 on 2023-04-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_rename_homedecor_homedcor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homedecordetail',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homefurnishingdetail',
            name='image',
        ),
        migrations.AddField(
            model_name='homedcor',
            name='image',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homefurnishing',
            name='image',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
