# Generated by Django 3.2.18 on 2023-04-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20230429_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='homedecordetail',
            name='rank',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homefurnishingdetail',
            name='rank',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
