# Generated by Django 3.2.18 on 2023-04-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20230429_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('rank', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.FloatField()),
                ('price', models.TextField()),
                ('add_to_chart', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
