# Generated by Django 3.2.19 on 2023-05-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_auto_20230503_1612'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeFurnishing',
        ),
        migrations.DeleteModel(
            name='HomeFurnishingDetail',
        ),
    ]
