# Generated by Django 3.2.19 on 2023-05-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_auto_20230504_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='homedecordetail',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homedecordetail',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
